### ISSUE TITLE
Option to disable step reporting

### ISSUE THREAD

**Issue by kelvintaywl** [cucumber/cucumber-junit-xml-formatter#25]
### 🤔 What's the problem you're trying to solve?

The step reporting feature is great:
https://github.com/cucumber/cucumber-junit-xml-formatter?tab=readme-ov-file#step-reporting

_However_, for CI tools (e.g., CircleCI) that read in these JUnit XML reports, these <system-out> elements may not be necessary and can lead to file-size bloating.

### ✨ What's your proposed solution?

Would it be possible to allow the step-reporting to be toggled (e.g., turned off)?

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mpkorstanje** [comment]
As of yet your problem sounds somewhat theoretical. Do you have a concrete example where this is a problem. What orders of magnitude are we talking about?

Maven Surefire, Gradle, and the JUnit 5 Platform can generate very similar JUnit XMLs without the step reporting. Have you considered using any of these?

Note that Cucumber-JVM currently doesn't have a mechanism to pass arbitrary configuration options to plugins. You would have to wrap the `junit-xml-formatter` in your own `Plugin` implementation. So even if this were implemented, the ergonomics would be rather limited.

**Comment by kelvintaywl** [comment]
Hi @mpkorstanje thank you for the follow-up.
I noted that this is no longer an issue on our side.
I will close this request for now! thank you 🙇 

for context, we were seeing odd characters printed within the `<system-out><!CDATA>...` block.
ultimately, it meant the generated XML report could not be parsed on CircleCI.
I thus wonder if there was a quick way to disable the step-reporting.

**Comment by mpkorstanje** [comment]
Cheers. Did you manage to find the root cause of the odd characters? Generally speaking I would expect Cucumber not to print any odd characters (that weren't also in the feature file).
