### ISSUE TITLE
Use Exception.stackTrace

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-junit-xml-formatter#26]
### 🤔 What's the problem you're trying to solve?

I would like to render stack traces nicely. 

### ✨ What's your proposed solution?

In https://github.com/cucumber/messages/pull/182 the stacktrace property was added to messages. It isn't used yet in the formatter.

### ⛏ Have you considered any alternatives or workarounds?

Cucumber JVM currently writes the stacktrace into the `Exception.message` field.

### 📚 Any additional context?

I'm not sure in which field of the XML the stacktrace is supposed to go. This will need some integration testing. And this should also keep working in conjunction with the html formatter.

**Comment by mpkorstanje** [comment]
@davidjgoss did the use of `Exception.stackTrace` make it into `react-components yet?

**Comment by davidjgoss** [comment]
@mpkorstanje not yet - I'll put something together for that today.

I'm also not sure where a separate stack trace could/should go while remaining valid per the XSD. I asked the original requester in https://github.com/cucumber/cucumber-js/issues/2348#issuecomment-1892238648

**Comment by mpkorstanje** [comment]
Running Surefire (which produces JUnit XML like files) the xml should look like this:

```xml
    <failure message="expected: &lt;true&gt; but was: &lt;false&gt;" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at io.cucumber.skeleton.StepDefinitions.my_belly_should_growl(StepDefinitions.java:19)
	at ✽.my belly should growl(classpath:io/cucumber/skeleton/belly.feature:6)
]]></failure>
```

So the stacktrace goes into the element, the exception message is the message and the type is the class of the exception.

**Comment by davidjgoss** [comment]
React components change: https://github.com/cucumber/react-components/pull/345
