### ISSUE TITLE
Junit Plugin to include more properties to bring it in line with the extra properties in json plugin

### ISSUE THREAD

**Issue by mjordanBetBright** [cucumber/cucumber-junit-xml-formatter#4]
### 🤔 What's the problem you're trying to solve?

The cucumber junit xml file doesn't contain as much info as the cucumber json plugin (e.g. scnenario.attach() adds this info to json but not xml)

### ✨ What's your proposed solution?

To make the junit plugin contain more info related to cucumber tests. Admittedly, there is _a lot_ of info in the json plugin, so perhaps making junit plugin configureable to include what each user needs

### ⛏ Have you considered any alternatives or workarounds?

I have considered a custom class to make these changes, but I feel that there should be consistency in what each cucumber reporting plugins provide

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mattwynne** [comment]
@mjordanBetBright can you be specific about the information you'd like to see added to the JUnit report?

**Comment by mjordanBetBright** [comment]
Hello @mattwynne , I propose adding properties elements to the junit testcase element that match info contained in the Before and After Hooks. Also a scenario property that contains information added to the scenario object throughout the test. e.g. similar to below

```
    <testcase classname="Test Feature" name="Failing Test" time="44.206">
        <properties>
            <property name="before" value="before Hook"/>
        </properties>
    </testcase>
```
I'm testing if possible to add screenshots, etc. to a property, will post if successful. But that's the idea.

One problem I see is that reporting tools will post these properties regardless (that's the case with Testmo anyway). I think it should be important that to include these properties in a report, it should be strictly opt in. e.g. this is how testmo.com displays the above test case when submitted. I haven't tried other reporting tools

![Screenshot 2023-01-06 at 11 25 21](https://user-images.githubusercontent.com/30830739/211003591-3ae8cbd0-7b57-463b-ab6e-ef6cf824702c.png)

**Comment by mpkorstanje** [comment]
I don't think this the intended purpose of the properties element. It appears to be for system and/or environment properties. Additionally it doesn't appear to be legal in that position. 

While this extension might be understood in some systems, the Jenkins XSD is a defacto standard. So to ensure it is understood by the largest group consumers it is important we stick very close to the schema and the intended use.

But perhaps you can explain the underlying problemen you are trying to solve first. What extra information do you need, and what do you need it for?

Once we know that we can work out which features might be useful for a larger public and for which you may want to fork and maintain your own implementation.

**Comment by mjordanBetBright** [comment]
Hi @mpkorstanje , yeah the more I look into the properties element, the more I see it's probably not a good fit. I'll look into the Jenkins XSD standard instead of my own reporting tool as well.

As for the problem I see, information can be recorded during the run of a scenario (e.g. screenshots for failed tests, Thread ID) and we add this information to the scenario using scenario.attach(). This info is added in either the @Before or @After hook. It's important information for the outcome of a test (especially screenshots, posting the failing test screenshot to our reporting tool is a use case)

I believe this is relatively common practice for users of Cumber? (e.g. using the After hook to record information about said test). If not, I can reevaluate our implemetation or maybe use the json report, which contains all info needed

**Comment by mpkorstanje** [comment]
I reckon it is unlikely that you will be able to get this information into your tooling by going through the XML report. Especially screenshots. So you may want to consider checking the documentation of your tooling and see if they have an Rest API that you can use directly.

For example [I see that TestMo supports attaching links to files](https://docs.testmo.com/api/reference/automation-runs). Presumably files that were attached as artifacts in the CI system. I reckon you should explore that avenue instead.

**Comment by mpkorstanje** [comment]
For a more long term approach you could look at [Open Test Reporting ](https://github.com/ota4j-team/open-test-reporting). This is part of JUnit 5 and supports attachments. Though the attachment support is  currently limited to supporting simple key-value pairs without any meta information about the value. You could perhaps work out an extension to allow for more complex data to be supported.

**Comment by mjordanBetBright** [comment]
Hey, thanks for going above and beyond and looking into that @mpkorstanje , yeah we looked at the API and I think we'll probably use that as well. So I reckon this feature request can probably be closed? I don't think for overall cucumber support, this is a feature worth implementing (e.g. info stored in before/after hooks being included in xml report)?

**Comment by mpkorstanje** [comment]
Perhaps, but there has been no interest in the last decade. :smile:
